name: brew

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  brew:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Fetch Homebrew Analytics and GitHub Stars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mise run fetch-stats
          mise run fetch-competitors
          mise run fetch-hk-competitors
          mise run fetch-top-repos

      - name: Generate plots
        run: |
          mise run plot-stats
          mise run plot-hk-stats
          mise run plot-top-repos
          mise run plot-brew-rankings
          mise run plot-mise-brew-rank
          mise run generate-fastest-growing

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.csv *.txt charts/*.png
          git diff --cached
          COMMIT_MSG=$(uv run python mise-tasks/generate-commit-message.py)
          git commit -m "$COMMIT_MSG" || exit 0
          git push

permissions:
  contents: write
